name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  
  web-build-test:
  
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v3
    - name: Wasm pack 
      uses: jetli/wasm-pack-action@v0.3.0
    - name: Web Build
      run: wasm-pack build
    - name: Web Test
      run: wasm-pack test
    
