name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v1
    - name: Wasm pack 
      uses: jetli/wasm-pack-action@v0.3.0
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Web Test
      run: wasm-pack test --node
